query getUsers {
    getUsers {
        name
        id
    }
}

query loggedInUser {
    loggedInUser {
        name
    }
}

mutation register($name: String!) {
    register(name: $name) {
        name
    }
}

subscription getNewUsers {
    getNewUsers {
        id,
        name
    }
}

subscription subscribeToChatMessages {
    getNewMessages{
        message,
        date,
        user {
            name
        }
    }
}

mutation sendMessage($message: String!) {
    sendMessage(message: $message) {
        message,
        date
    }
}