[package]
name = "lyng2"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.3.0"
chrono = "0.4.19"
log = "0.4.17"
ron = "0.7.0"
serde = "1.0.136"
simplelog = "0.12.0"
websocket = { version = "0.26.4", features = ["sync"] }
parser_combinator = { git = "https://github.com/ekinimo/Kirby", branch = 'main' }