[package]
name = "lyng2"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.3.0"
chrono = "0.4.19"
futures-util = "0.3.24"
log = "0.4.17"
ron = "0.7.0"
serde = "1.0.136"
simplelog = "0.12.0"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
warp = "0.3.2"
parser_combinator = { git = "https://github.com/ekinimo/Kirby", branch = 'main' }