name: Lyng2

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            server/target/
          key: cargo-build-${{ hashFiles('server/Cargo.toml') }}
      - name: Build
        run: cd server && cargo build --verbose
      - name: Run tests
        run: cd server && cargo test --verbose

  rustChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            server/target/
          key: cargo-build-${{ hashFiles('server/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - name: rustfmt
        run: cd server && cargo fmt --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path server/Cargo.toml -- -D warnings

  react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: cd client && npm install
      - name: Build
        run: cd client && npm run build
      - name: Test
        run: cd client && npm test

  reactChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: cd client && npm install
      - name: Prettier
        run: cd client && npx prettier --check src
      - name: Eslint
        run: cd client && npx eslint src --ext .js,.jsx,.ts,.tsx
